### ISSUE TITLE
VimBootstrapUpdate / vim-bootstrap.appspot.com offline

### ISSUE THREAD

**Issue by henriquechehad** [avelino/vim-bootstrap#213]
The URL https://vim-bootstrap.appspot.com/langs is returning error not found:

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/Users/henriquechehad/.vim/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.py", line 24, in get_available_langs
    resp = urllib2.urlopen("https://vim-bootstrap.appspot.com/langs")
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by avelino** [comment]
We need to create a code to redirect, that stay on google app engine, today is `python`

**Comment by avelino** [comment]
@henriquechehad fixed run:

    :PlugUpdate

Reopen and run:

    :VimBootstrapUpdate
