### ISSUE TITLE
Update failed, how to fix it?

### ISSUE THREAD

**Issue by ning05130513** [avelino/vim-bootstrap#216]
I followed the instructions but got error, does it matters?
> Updating to the latest version
> 
> :VimBootstrapUpdate (thanks to @sherzberg)
> :PlugInstall

```
Error detected while processing function VimBootstrapUpdate:                                                                 
line   24:                                                                                                                   
Traceback (most recent call last):                                                                                           
  File "<string>", line 10, in <module>                                                                                      
  File "/Users/ninggw/.vim/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.py", line 24, in get_available_langs   
    resp = urllib2.urlopen("https://vim-bootstrap.com/langs")                                                                
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163
, in urlopen                                                                                                                 
    return opener.open(url, data, timeout)                                                                                   
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472
, in open                                                                                                                    
    response = meth(req, response)                                                                                           
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582
, in http_response                                                                                                           
    'http', request, response, code, msg, hdrs)                                                                              
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510
, in error                                                                                                                   
    return self._call_chain(*args)                                                                                           
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444
, in _call_chain                                                                                                             
    result = func(*args)                                                                                                     
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590
, in http_error_default                                                                                                      
    raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                       
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by cassiobotaro** [comment]
@ning05130513 we are changing from Python to Go, and VimBootstapUpdater is temporarily unavailable.
If you want to update vim-bootstrap, you have to do it manually(generating another .vimrc by hand).
Sorry about that, we fixing this as soon as possible. 
If you already at version using vim-plug, you can use :PlugUpdate to update all plugins.

**Comment by avelino** [comment]
Fixed @ning05130513 
Run
```
:PlugUpdate
```
close, reopen and run:
```
:VimBootstrapUpdate
```
