### ISSUE TITLE
almost 200ms startup time for vim-bootstrap on Neovim

### ISSUE THREAD

**Issue by xbeta** [avelino/vim-bootstrap#217]
using the [https://github.com/bchretien/vim-profiler](vim-profiler) to test

```
─± ./vim-profiler.py nvim
Running nvim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/xbeta/.config/nvim/plugged
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1	192.755   vim-bootstrap-updater
2	 21.552   vim-colorschemes
3	 21.412   syntastic
4	 10.918   python-mode
5	  8.861   vim-airline
6	  6.116   tagbar
7	  5.176   vim-session
8	  4.892   vim-fugitive
9	  4.865   vim-polyglot
10	  4.480   jedi-vim
=====================================
```

Why is it 10x slower than the 2nd item on the list?

**Comment by xbeta** [comment]
`:VimBootstrapUpdate` also got this

```
Error detected while processing function VimBootstrapUpdate[24]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/Users/xbeta/dotfiles/config/nvim.symlink/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.py", line 24, in get_available_langs
    resp = urllib2.urlopen("https://vim-bootstrap.com/langs")
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/loca
Press ENTER or type command to continue
```

**Comment by avelino** [comment]
Fixed @xbeta  
Run
```
:PlugUpdate
```
close, reopen and run:
```
:VimBootstrapUpdate
```

**Comment by avelino** [comment]
Vim
```
====================================
Top 10 plugins slowing vim's startup
====================================
1        25.226   nerdtree
2        24.910   vim-bracketed-paste
3        20.668   vim-bootstrap-updater
4        19.977   syntastic
5        13.520   c.vim
6         7.904   vim-polyglot
7         6.349   vim-airline
8         4.461   delimitMate
9         4.064   tagbar
10        3.773   vim-fugitive
====================================
```
NeoVim
```
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1        20.585   nerdtree
2        13.419   vim-bracketed-paste
3        12.062   syntastic
4         9.450   c.vim
5         4.776   vim-airline
6         4.247   vim-polyglot
7         4.246   vim-fugitive
8         3.467   vim-bootstrap-updater
9         3.231   delimitMate
10        2.884   tagbar
=====================================
```
