### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by xbeta** [avelino/vim-bootstrap#219]
@avelino 
After testing the update from  #217 , Now I hit another error:

```
Error detected while processing function VimBootstrapUpdate[24]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/xbeta/dotfiles/config/nvim.symlink/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.py", line 11, in <module>
    reload(sys)
NameError: name 'reload' is not defined

```

And still slow:

```
╰─± ./vim-profiler.py nvim
Running nvim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/xbeta/.config/nvim/plugged
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1	122.058   vim-bootstrap-updater
2	 20.054   vim-colorschemes
3	 15.505   syntastic
4	  8.262   python-mode
5	  6.766   vim-airline
6	  4.019   vim-polyglot
7	  3.988   tagbar
8	  3.740   vim-fugitive
9	  3.445   vim-session
10	  3.101   jedi-vim
=====================================

```

**Comment by cassiobotaro** [comment]
Thanks to report! I've done a PR to fix that. https://github.com/avelino/vim-bootstrap-updater/pull/12

**Comment by cassiobotaro** [comment]
@xbeta  `:PlugUpdate` to update the plugin and try again.

**Comment by xbeta** [comment]
@cassiobotaro Thx, the first error is fixed, though performance is as-slow.

**Comment by cassiobotaro** [comment]
Bug confirmed! I checking...
![image](https://cloud.githubusercontent.com/assets/3127847/20636007/c0087340-b34c-11e6-907d-1acdad97bc26.png)

**Comment by cassiobotaro** [comment]
Fixed with https://github.com/avelino/vim-bootstrap-updater/commit/2c21289cb89b86bf0b04e8d5fe52e446a029e5b7

@xbeta Can you check?, if it's ok, please close this issue.

**Comment by xbeta** [comment]
Seems to be Ok now.

```
╰─± /Users/xbeta/.config/nvim/vim-profiler.py nvim
Running nvim to generate startup logs... done.
Loading and processing logs... done.
Plugin directory: /Users/xbeta/.config/nvim/plugged
=====================================
Top 10 plugins slowing nvim's startup
=====================================
1	 19.126   vim-colorschemes
2	 14.831   syntastic
3	  9.513   python-mode
4	  6.176   vim-airline
5	  3.964   vim-polyglot
6	  3.907   vim-fugitive
7	  3.621   vim-session
8	  3.432   tagbar
9	  3.231   jedi-vim
10	  3.217   delimitMate
=====================================
```
